name: 'file-description-auto-generator'
description: 'generate summary or description for repo files by using AI'
author: 'mx_in'
inputs:
  openai-api-key:
    description: 'Your openai api key'
    required: true
  openai-prompt:
    description: 'The OpenAI prompt'
    require: true
  model:
    description: 'The model to use'
    required: false
    default: 'text-davinci-003'
  input-files:
    description: 'The files which as AI inputs'
    require: true
  output-file-name:
    description: 'The out put file name for AI generate text'
    require: true
  rewrite:
    description: 'The tag that if the exist output should be rewriten'
    require: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
